#!/bin/sh

# Production environment
export RAILS_ENV="production"
export DATABASE_URL="postgres://$APP_NAME:$APP_NAME@localhost/$APP_NAME"
ruby $KEROHU_PATH/database.yml.rb > $CURRENT_RELEASE_APP_PATH/config/database.yml

run_quietly "cd ${CURRENT_RELEASE_APP_PATH}"
run_quietly "mkdir -p ${CURRENT_RELEASE_APP_PATH}/vendor/"
SHARED_LOG_PATH="${SHARED_APP_PATH}/log/"
run_quietly "mkdir -p ${SHARED_LOG_PATH}"
run_quietly "mkdir -p ${SHARED_APP_PATH}/tmp/pids/"
run_quietly "mkdir -p ${SHARED_APP_PATH}/bundle/"
run_quietly "mkdir -p ${SHARED_APP_PATH}/data/"
run_quietly "ln -nfs ${SHARED_APP_PATH}/data/ ${CURRENT_RELEASE_APP_PATH}/public/data"
#ln -nfs ${SHARED_APP_PATH}/config/database.yml ${CURRENT_RELEASE_APP_PATH}/config/database.yml || exit_with_error
run_quietly "rm -rf ${CURRENT_RELEASE_APP_PATH}/log"
run_quietly "ln -nfs ${SHARED_LOG_PATH} ${CURRENT_RELEASE_APP_PATH}/log"
run_quietly "mkdir -p ${CURRENT_RELEASE_APP_PATH}/tmp/"
run_quietly "ln -nfs ${SHARED_APP_PATH}/tmp/pids/ ${CURRENT_RELEASE_APP_PATH}/tmp/pids"
run_quietly "mkdir -p ${CURRENT_RELEASE_APP_PATH}/vendor/"
run_quietly "ln -nfs ${SHARED_APP_PATH}/bundle/ ${CURRENT_RELEASE_APP_PATH}/vendor/bundle"

# init rbenv
run_quietly "[ -d $RBENV_PATH ] && export PATH=\"$RBENV_PATH/bin:$PATH\" && eval \"\$(rbenv init - sh)\" && rbenv rehash"
log "ruby version : `ruby -v`"


# dependencies
log "Installing dependencies using `bundle --version`"
run_quietly "unset GIT_DIR"
#run "bundle install --deployment --without development test"
run "bundle install --without development:test --path vendor/bundle --binstubs bin/ --deployment"


# database
if [[ $DEPLOY_MIGRATE ]]; then
  log "Migrating database"
  run "bundle exec rake db:migrate"
else
  log "No database migration in production"
fi

log "Successfully deployed application to ${CURRENT_RELEASE_APP_PATH}"

log "Preparing application"
run "bundle exec rake assets:precompile"

log "Linking as current"
rm -f ${OLD_CURRENT_APP_PATH} 2> /dev/null
mv -f ${CURRENT_APP_PATH} ${OLD_CURRENT_APP_PATH} 2> /dev/null
run_quietly "ln -nfs ${CURRENT_RELEASE_APP_PATH} ${CURRENT_APP_PATH}"


log "Restarting application"
#bin/unicorn -E production -c config/unicorn.rb config.ru
#${OLD_CURRENT_APP_PATH}/bin/god terminate
#${CURRENT_APP_PATH}/bin/god -c ${CURRENT_APP_PATH}/config/unicorn.god
#     bundle exec foreman export bluepill /tmp -u app -l ~/work/fourmi2/log
bundle exec foreman export bluepill $CURRENT_APP_PATH -u $USER -l $SHARED_LOG_PATH -d $CURRENT_APP_PATH -a $APP_NAME
#mkdir -p tmp/
#touch tmp/restart.txt


