#!/bin/bash

run_quietly() {
  eval $1 || exit_with_error $1
}

run() {
  echo "running : $1"
  run_quietly "$1"
}

log() {
  echo "-----> $*"
}

exit_with_error() {
  log "An error has occurred, stopping\nInvoked command : $1"
  exit 1
}

if ! [ -t 0 ]; then
  read -a ref
fi
IFS='/' read -ra REF <<< "${ref[2]}"
export CURRENT_GIT_BRANCH="${REF[2]}"


#if [ "master" != "$branch" ]; then
#  echo "pushed into branch $branch. Done"
#  exit
#fi

export USER=`id -nu`
export CURRENT_GIT_DIR=`pwd`
export APP_NAME=`basename $CURRENT_GIT_DIR .git`


#if [[ ! $RBENV_PATH ]]; then
#  RBENV_PATH=$HOME/.rbenv
#fi

#kerohu_install_hook() {
#  cat << EOF
##!/bin/bash
#KEROHU_PATH="/home/app/kerohu"
#echo "KEROHU_PATH : $KEROHU_PATH"
#echo "loading functions"
#. \$KEROHU_PATH/kerohu-fonctions
#echo "running post-receive"
#. \$KEROHU_PATH/post-receive-deploy
#EOF
#}

